[package]
name = 'hwpr'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'hwpr'

[dependencies]
extendr-api = '0.4.0'
hwp = "0.2.0"
libR-sys = { version = "0.4.0", features = ["clang"] }
